include( ./ui/ui.pri )
include( ./motion/motion.pri )
include( ./config/config.pri )
include( ./crashHandler/crashHandler.pri )
include( ./cameraFactory/cameraFactory.pri )
include( ./jointDetection/jointDetection.pri )
include( ./telecentricLineCalibrator/telecentricLineCalibrator.pri )
include( ./test/test.pri )
include(./workpieceEdgeAssembly/workpieceEdgeAssembly.pri)
include(./utils/utils.pri)
include(./resultProcessing/resultProcessing.pri)
