include( ./ui/ui.pri )
include( ./rail/rail.pri )
include( ./config/config.pri )
include( ./crashHandler/crashHandler.pri )
include( ./cameraFactory/cameraFactory.pri )
include( ./jointDetection/jointDetection.pri )
include( ./telecentricLineCalibrator/telecentricLineCalibrator.pri )
include( ./test/test.pri )
include(./workpieceEdgeAssembly/workpieceEdgeAssembly.pri)
include(./utils/utils.pri)
include(./dxfSaver/dxfSaver.pri)
include(./transferResult/transferResult.pri)
