#ifndef PLC_VARIABLEADDRESS_H
#define PLC_VARIABLEADDRESS_H

extern int PLC1_Id;
// B0-B32767 (0x3000-0xAFFF)
extern int X_ServoEnable;
extern int X_Stop;
extern int X_Reset;
extern int X_JogForward;
extern int X_JogReverse;
extern int X_HomeCommand;
extern int X_AbsPositionCommand;
extern int X_RelPositionCommand;
extern int X_TorqueCommand;
extern int X_ImmediateStop;
extern int X_Acceleration;
extern int X_Deceleration;
extern int X_CurveType;
extern int TEST;
// R0-R32767 (0x3000-0xAFFF)
extern int X_JogSpeed;
extern int X_AbsPosition;
extern int X_AbsSpeed;
extern int X_RelPosition;
extern int X_RelSpeed;
extern int X_TorqueForce;
extern int X_TorqueSpeed;

// S0-S4095 (0xE000-0xEFFF)
extern int X_PosLimitSignal;
extern int X_PosLimitAlarm;
extern int X_NegLimitSignal;
extern int X_NegLimitAlarm;
extern int X_HomeSignal;
extern int X_EnableComplete;
extern int X_StopComplete;
extern int X_ResetComplete;
extern int X_AbsPosComplete;
extern int X_DriverAlarm;
extern int X_AxisFault;
extern int X_FBError;
extern int X_RelativeMoving;
extern int X_RelativePosHolding;
extern int X_RelativePosComplete;
extern int X_AbsoluteMoving;
extern int X_AbsolutePosHolding;
extern int X_AbsolutePosComplete;
extern int X_HomingMoving;
extern int X_HomingHolding;
extern int X_HomingComplete;
extern int X_JogRunning;
extern int X_IStopDone;
extern int X_IStopError;
// D0-D7999 (0x0000-0x1F3F)
extern int X_CurrentPosition;
extern int X_CurrentSpeed;
extern int X_CurrentTorque;
extern int X_DriverFaultCode;
extern int X_AxisFaultCode;
#endif  // PLC_VARIABLEADDRESS_H
